# Generated by Django 4.2.1 on 2023-08-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='superpower',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
