# Generated by Django 4.2.1 on 2023-08-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rename_desc_agent_description_alter_superpower_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='agent',
            new_name='owner',
        ),
    ]
